# Before Script
before_script:
  - apt-get update -yqq
  - apt-get install git -yqq

# Stages
stages:
  - test

# Image from https://github.com/splitbrain/docker-phpfarm
image: splitbrain/phpfarm:jessie

# PHP5.3
php:5.3:
  stage: test
  script:
      - echo "Running PHPUnit Tests on PHP5.3"
      - wget https://getcomposer.org/composer.phar -O composer
      - php-5.3 composer install
      - wget https://phar.phpunit.de/phpunit-old.phar -O phpunit
      - php-5.3 phpunit -d memory_limit=512M --colors --debug  --coverage-text

# PHP5.4
php:5.4:
  stage: test
  script:
      - echo "Running PHPUnit Tests on PHP5.4"
      - wget https://getcomposer.org/composer.phar -O composer
      - php-5.4 composer install
      - wget https://phar.phpunit.de/phpunit-old.phar -O phpunit
      - php-5.4 phpunit -d memory_limit=512M --colors --debug  --coverage-text

# PHP5.5
php:5.5:
  stage: test
  script:
      - echo "Running PHPUnit Tests on PHP5.5"
      - wget https://getcomposer.org/composer.phar -O composer
      - php-5.5 composer install
      - wget https://phar.phpunit.de/phpunit-old.phar -O phpunit
      - php-5.5 phpunit -d memory_limit=512M --colors --debug  --coverage-text

# PHP5.6
php:5.6:
    image: php:5.6
    script:
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install
      - echo "Running PHPUnit Tests on PHP5.6"
      - php vendor/bin/phpunit --colors --debug  --coverage-text

# PHP7.0
php:7.0:
    image: php:7.0
    script:
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install
      - echo "Running PHPUnit Tests on PHP7.0"
      - php vendor/bin/phpunit --colors --debug  --coverage-text

# PHP7.1
php:7.1:
    image: php:7.1
    script:
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install
      - echo "Running PHPUnit Tests on PHP7.1"
      - php vendor/bin/phpunit --colors --debug  --coverage-text